version: '3'

services:
  edens-website:
    build:
      context: .
      args:
        NUXT_PORT: ${NUXT_PORT}
        NUXT_HOST: ${NUXT_HOST}
    container_name: "nuxt-template"
    env_file: .env
    ports:
      - '3001:${NUXT_PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
